# a docker-compose.yml to start a simple cluster with three ZooKeeper nodes and three Solr nodes.
#
# To use:
# docker-compose up
#
version: '3.7'
services:
  solr1:
    container_name: solr1
    image: codice/ddf-solr:2.17.0-SNAPSHOT
    ports:
      - 8981:8981
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_PORT=8981
      - SOLR_HOST=solr1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - solr

  solr2:
    container_name: solr2
    image: codice/ddf-solr:2.17.0-SNAPSHOT
    ports:
      - 8982:8982
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_PORT=8982
      - SOLR_HOST=solr2
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - solr

  solr3:
    container_name: solr3
    image: codice/ddf-solr:2.17.0-SNAPSHOT
    ports:
      - 8983:8983
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_PORT=8983
      - SOLR_HOST=solr3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - solr

  zoo1:
    image: zookeeper:3.4.14
    container_name: zoo1
    restart: always
    ports:
      - 2181:2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo2:
    image: zookeeper:3.4.14
    container_name: zoo2
    restart: always
    ports:
      - 2182:2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo3:
    image: zookeeper:3.4.14
    container_name: zoo3
    restart: always
    ports:
      - 2183:2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

networks:
  solr: